name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY:latest

    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        # IMAGE_NAME: "user_id/image_name"
        # TAG_NAME: "v0.0.1"
        LATEST: "true"
