name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY:latest

    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.GITHUB_USERNAME }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        REGISTRY: "docker.pkg.github.com"
        TAG_NAME: "latest"
        LATEST: "true"
