name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY:latest
  
    - name: Push the Docker image to GitHub Package Registry
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY:latest
  
